# Generated by Django 5.2.5 on 2025-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_joining',
            new_name='leaving_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_leaving',
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('current', 'Current'), ('past', 'Past')], default='current', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leaving_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
